#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.




submenu "Advanced options for Ubuntu"{


menuentry "Ubuntu, with Linux 3.18.7-ck1-mzn" --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-3.18.7-ck1-mzn-advanced-a43c13f7-56a1-4be8-bb42-0cdb8e5f25df' {
		recordfail
	savedefault
		load_video
		gfxmode $linux_gfx_mode
		insmod gzio
		insmod part_msdos
		insmod btrfs
		set root='hd0,msdos7'
		if [ x$feature_platform_search_hint = xy ]; then
		  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos7 --hint-efi=hd0,msdos7 --hint-baremetal=ahci0,msdos7  a43c13f7-56a1-4be8-bb42-0cdb8e5f25df
		else
		  search --no-floppy --fs-uuid --set=root a43c13f7-56a1-4be8-bb42-0cdb8e5f25df
		fi
		echo	'Loading Linux 3.18.7-ck1-mzn ...'
		linux	/@/boot/vmlinuz-3.18.7-ck1-mzn root=UUID=a43c13f7-56a1-4be8-bb42-0cdb8e5f25df ro rootflags=subvol=@  quiet splash resume=/dev/sda5 $vt_handoff
		echo	'Loading initial ramdisk ...'
		initrd	/@/boot/initrd.img-3.18.7-ck1-mzn
}


menuentry "Ubuntu, with Linux 3.18.7-ck1-mzn (recovery mode)" --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-3.18.7-ck1-mzn-recovery-a43c13f7-56a1-4be8-bb42-0cdb8e5f25df' {
		recordfail
		load_video
		insmod gzio
		insmod part_msdos
		insmod btrfs
		set root='hd0,msdos7'
		if [ x$feature_platform_search_hint = xy ]; then
		  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos7 --hint-efi=hd0,msdos7 --hint-baremetal=ahci0,msdos7  a43c13f7-56a1-4be8-bb42-0cdb8e5f25df
		else
		  search --no-floppy --fs-uuid --set=root a43c13f7-56a1-4be8-bb42-0cdb8e5f25df
		fi
		echo	'Loading Linux 3.18.7-ck1-mzn ...'
		linux	/@/boot/vmlinuz-3.18.7-ck1-mzn root=UUID=a43c13f7-56a1-4be8-bb42-0cdb8e5f25df ro recovery nomodeset rootflags=subvol=@ 
		echo	'Loading initial ramdisk ...'
		initrd	/@/boot/initrd.img-3.18.7-ck1-mzn
}


menuentry "Ubuntu, with Linux 3.13.0-46-generic" --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-3.13.0-46-generic-advanced-a43c13f7-56a1-4be8-bb42-0cdb8e5f25df' {
		recordfail
	savedefault
		load_video
		gfxmode $linux_gfx_mode
		insmod gzio
		insmod part_msdos
		insmod btrfs
		set root='hd0,msdos7'
		if [ x$feature_platform_search_hint = xy ]; then
		  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos7 --hint-efi=hd0,msdos7 --hint-baremetal=ahci0,msdos7  a43c13f7-56a1-4be8-bb42-0cdb8e5f25df
		else
		  search --no-floppy --fs-uuid --set=root a43c13f7-56a1-4be8-bb42-0cdb8e5f25df
		fi
		echo	'Loading Linux 3.13.0-46-generic ...'
		linux	/@/boot/vmlinuz-3.13.0-46-generic root=UUID=a43c13f7-56a1-4be8-bb42-0cdb8e5f25df ro rootflags=subvol=@  quiet splash resume=/dev/sda5 $vt_handoff
		echo	'Loading initial ramdisk ...'
		initrd	/@/boot/initrd.img-3.13.0-46-generic
}

menuentry "Ubuntu, with Linux 3.13.0-46-generic (recovery mode)" --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-3.13.0-46-generic-recovery-a43c13f7-56a1-4be8-bb42-0cdb8e5f25df' {
		recordfail
		load_video
		insmod gzio
		insmod part_msdos
		insmod btrfs
		set root='hd0,msdos7'
		if [ x$feature_platform_search_hint = xy ]; then
		  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos7 --hint-efi=hd0,msdos7 --hint-baremetal=ahci0,msdos7  a43c13f7-56a1-4be8-bb42-0cdb8e5f25df
		else
		  search --no-floppy --fs-uuid --set=root a43c13f7-56a1-4be8-bb42-0cdb8e5f25df
		fi
		echo	'Loading Linux 3.13.0-46-generic ...'
		linux	/@/boot/vmlinuz-3.13.0-46-generic root=UUID=a43c13f7-56a1-4be8-bb42-0cdb8e5f25df ro recovery nomodeset rootflags=subvol=@ 
		echo	'Loading initial ramdisk ...'
		initrd	/@/boot/initrd.img-3.13.0-46-generic
}


}




