#!/bin/sh
#THIS IS A GRUB PROXY SCRIPT
'/etc/grub.d/proxifiedScripts/linux' | /etc/grub.d/bin/grubcfg_proxy "-'SUBMENU' as 'Advanced options for Arch Linux'{-'Advanced options for Arch Linux'/'Arch Linux, with Linux linux-mzn (fallback initramfs)'~17116be66d39950b330323d885e9c694~, -'Advanced options for Arch Linux'/'Arch Linux, with Linux linux-lts (fallback initramfs)'~18289c140de66c43df03b81648a7a425~, -'Advanced options for Arch Linux'/'Arch Linux, with Linux linux-ck-nehalem (fallback initramfs)'~4c1e12fb63a20102bd97641fef3aa8ab~}
+*
+#text
+'Arch Linux'~78bf054070883689d517a4254ac79e78~
+'Advanced options for Arch Linux'/*
+'Advanced options for Arch Linux'/'Arch Linux, with Linux linux-mzn'~c2752e91a9c4c3b1e1dc045b711a397a~
+'Advanced options for Arch Linux'/'Arch Linux, with Linux linux-ck-nehalem'~88b8bb4f4d82deefc96b5d7670836816~
+'Advanced options for Arch Linux'/'Arch Linux, with Linux linux-lts'~4d0174719831c79d5f47793708b68fae~
"